QuizApplication/QuizApplication/Models/Quiz.cs
using System.ComponentModel.DataAnnotations;

namespace QuizApplication.Models
{
    public class Quiz
    {
        [Key]
        public string Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string CreatorId { get; set; }
    }
}

QuizApplication/QuizApplication/Models/ScoreBoard.cs
using System.ComponentModel.DataAnnotations;

namespace QuizApplication.Models
{
    public class ScoreBoard
    {
        [Key]
        public string Id { get; set; }
        public string QuizId { get; set; }
        public ICollection<UserScore> UserScores { get; } = new List<UserScore>();

        public ScoreBoard(string id, string quizId)
        {
            Id = id;
            QuizId = quizId;
        }
    }
}

QuizApplication/QuizApplication/Pages/AddQuiz.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using QuizApplication.Interfaces;
using QuizApplication.Models;

namespace QuizApplication.Pages
{
    public class AddQuizModel : PageModel
    {
        [BindProperty]
        public Quiz? Quiz { get; set; }
        private IQuizService _quizService { get; set; }

        public AddQuizModel(IQuizService service)
        {
            _quizService = service;
        }

        public IActionResult OnPost()
        {
            _quizService.AddQuiz(Quiz);
            
            return Redirect("/Quizzes");
        }
    }
}

QuizApplication/QuizApplication/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace QuizApplication.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

QuizApplication/QuizApplication/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using QuizApplication.Interfaces;
using QuizApplication.Models;

namespace QuizApplication.Pages
{
    public class IndexModel : PageModel
    {
        private IHttpContextAccessor _httpContextAccessor;
        private IUserServices _userServices { get; set; }

        [BindProperty]
        public string UserName { get; set; }

        [BindProperty]
        public string Password { get; set; }

        public IndexModel(IUserServices service, IHttpContextAccessor httpContextAccessor)
        {
            _httpContextAccessor = httpContextAccessor;
            _userServices = service;
        }

        public IActionResult OnPost()
        {
            User User = _userServices.Login(UserName, Password);
            if(User != null)
            {
                _httpContextAccessor.HttpContext.Session.SetString("UserId", User.Id);
                _httpContextAccessor.HttpContext.Session.SetString("UserName", User.UserName);
                return Redirect("/Quizzes");
            }
            return Page();
        }
    }
}

QuizApplication/QuizApplication/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace QuizApplication.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

QuizApplication/QuizApplication/Pages/Quiz.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using QuizApplication.Interfaces;
using QuizApplication.Models;
using Newtonsoft.Json;

namespace QuizApplication.Pages
{
    public class QuizModel : PageModel
    {
        [BindProperty]
        public Quiz? Quiz { get; set; }

        public string QuizId { get; set; }

        [BindProperty]
        public List<Question> QuestionList { get; set; }

        private IQuizService _quizService {  get; set; }

        private IHttpContextAccessor _httpContextAccessor { get; set; }

        public QuizModel(IQuizService service, IHttpContextAccessor httpContextAccessor)
        {
            _quizService = service;
            _httpContextAccessor = httpContextAccessor;
        }

        public void OnGet([FromQuery] string id)
        {
            Quiz = _quizService.GetQuizById(id);
            QuizId = id;
            QuestionList = _quizService.GetQuestionByQuizId(id);
            _httpContextAccessor.HttpContext.Session.SetString("QuestionList", JsonConvert.SerializeObject(QuestionList));
        }

        public IActionResult OnPost()
        {
            bool UpdateSuccess = _quizService.UpdateQuiz(Quiz.Id, Quiz);
            if(UpdateSuccess)
            {
                return Redirect("/Quizzes");
            }

            return Page();
        }

        public IActionResult OnPostSaveQuestions()
        {
            int questionCount = int.Parse(Request.Form["QuestionCount"]);

            var questionListJson = HttpContext.Session.GetString("QuestionList");
            var previousQuestionList = JsonConvert.DeserializeObject<List<Question>>(questionListJson);


            if (questionCount != previousQuestionList.Count) // Add first
            {
                for (int i = previousQuestionList.Count + 1; i <= questionCount; i++)
                {
                    var question = new Question(
                        Guid.NewGuid().ToString(),
                        Request.Form["QuizId"],
                        Request.Form["Question" + i],
                        Request.Form["correctAnswer_" + i],
                        Request.Form["Option1_" + i],
                        Request.Form["Option2_" + i],
                        Request.Form["Option3_" + i],
                        Request.Form["Option4_" + i]
                    );

                    _quizService.AddQuestion(question);
                }
            }

            bool updateSuccess = true;
            int index = 1;
            // Update 
            foreach (var question in previousQuestionList)
            {
                var updatedQuestion = new Question(
                        Guid.NewGuid().ToString(),
                        Request.Form["QuizId"],
                        Request.Form["Question" + index],
                        Request.Form["correctAnswer_" + index],
                        Request.Form["Option1_" + index],
                        Request.Form["Option2_" + index],
                        Request.Form["Option3_" + index],
                        Request.Form["Option4_" + index]
                );
                updateSuccess = _quizService.UpdateQuestion(question.Id, updatedQuestion);
                if (!updateSuccess)
                {
                    break;
                }
                index++;
            }

            if (!updateSuccess)
            {
                return Page();
            }
            return Redirect("/Quizzes");
        }
    }
}

QuizApplication/QuizApplication/Pages/Quizzes.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using QuizApplication.Interfaces;
using QuizApplication.Models;

namespace QuizApplication.Pages
{
    public class QuizzesModel : PageModel
    {
        public List<Quiz> Quizzes { get; set; }

        private IQuizService _quizService {  get; set; }

        public QuizzesModel(IQuizService service)
        {
            _quizService = service;
        }
        public void OnGet()
        {
            Quizzes = _quizService.GetAllQuizzes();
        }
    }
}

QuizApplication/QuizApplication/Pages/ScoreBoard.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using QuizApplication.Interfaces;
using QuizApplication.Models;

namespace QuizApplication.Pages
{
    public class ScoreBoardModel : PageModel
    {
        private IQuizService _quizService { get; set; }

        public List<UserScore> UserScoresList { get; set; }

        public ScoreBoardModel(IQuizService service)
        {
            _quizService = service;
        }

        public void OnGet([FromQuery] string id)
        {
            UserScoresList = _quizService.GetUserScoreList(id);
        }
    }
}

QuizApplication/QuizApplication/Pages/SignUp.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using QuizApplication.Interfaces;
using QuizApplication.Models;

namespace QuizApplication.Pages
{
    public class SignUpModel : PageModel
    {
        [BindProperty]
        public User? User { get; set; }
        private IUserServices _userServices { get; set; }

        public SignUpModel(IUserServices service)
        {
            _userServices = service;
        }
        public IActionResult OnPost()
        {
            User.generateID();
            _userServices.CreateUser(User);
            return Redirect("/Index");
        }
    }
}

QuizApplication/QuizApplication/Pages/StartQuiz.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;
using QuizApplication.Interfaces;
using QuizApplication.Models;

namespace QuizApplication.Pages
{
    public class StartQuizModel : PageModel
    {
        public List<Question> QuestionsList { get; set; }

        [BindProperty]
        public Quiz? Quiz { get; set; }

        public string QuizId { get; set; }

        private IQuizService _quizService {  get; set; }
        private IHttpContextAccessor _contextAccessor { get; set; }

        public StartQuizModel(IQuizService service, IHttpContextAccessor contextAccessor)
        {
            _quizService = service;
            _contextAccessor = contextAccessor;
        }

        public void OnGet([FromQuery] string Id)
        {
            Quiz = _quizService.GetQuizById(Id);
            QuestionsList = _quizService.GetQuestionByQuizId(Id);
            QuizId = Id;
            _contextAccessor.HttpContext.Session.SetString("QuestionList", JsonConvert.SerializeObject(QuestionsList));
        }

        public IActionResult OnPost()
        {
            int TotalCorrectAnswer = 0;
            var questionListJson = HttpContext.Session.GetString("QuestionList");
            var questionList = JsonConvert.DeserializeObject<List<Question>>(questionListJson);

            for(int i = 1; i <= questionList.Count(); i++)
            {
                string questionId = Request.Form["QuestionId_" + i];
                string userResult = Request.Form[questionId + " _" + i];
                string correctAnswer = _quizService.GetQuestionCorrectAnswer(questionId);

                UserResponse userResponse = new UserResponse(
                    Guid.NewGuid().ToString(),
                    userResult,
                    DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss")
                );

                _quizService.SubmitUserResponse(userResponse, questionId);

                // Calculate score
                if(userResult == correctAnswer)
                {
                    TotalCorrectAnswer++;
                }
            }

            // Save Score
            _quizService.AddUserScore(Request.Form["QuizId"], TotalCorrectAnswer);
            string quizId = Request.Form["QuizId"];
            return RedirectToPage("/ScoreBoard", new { id = quizId });
        }
    }
}

QuizApplication/QuizApplication/Pages/AddQuiz.cshtml
@page
@model QuizApplication.Pages.AddQuizModel
@{
    ViewData["Title"] = "Add Quiz";
}

<body>
    <div class="container">
        <h1>Add Quiz</h1>
        <!-- Add Quiz Information Section -->
        <form method="post">
            <label for="quizTitle">Quiz Title:</label>
            <input type="text" id="quizTitle" name="Title" required>
            <span asp-validation-for="@Model.Quiz.Title"></span>

            <label for="quizDescription">Quiz Description:</label>
            <textarea id="quizDescription" name="Description" rows="4" required></textarea>         
            <span asp-validation-for="@Model.Quiz.Description"></span>
            <button type="submit">Create Quiz</button>
        </form>
    </div>
</body>

QuizApplication/QuizApplication/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Quiz App Home Page";
}

<link rel="stylesheet" href="/QuizApplication.styles.css" />


<div class="text-center">
    <div class="login-container">
        <h2>Login</h2>
        <form method="post">
            <div class="form-group">
                <label for="username">Username:</label>
                <input type="text" id="username" name="Username" required>
            </div>
            <div class="form-group">
                <label for="password">Password:</label>
                <input type="password" id="password" name="Password" required>
            </div>
            <button type="submit">Login</button>
            <a href="/SignUp"><u>Click here to create an account</u></a>
        </form>
    </div>
</div>

QuizApplication/QuizApplication/Pages/Quiz.cshtml
@page "{Edit}"
@model QuizApplication.Pages.QuizModel
@{
    ViewData["Title"] = "Quiz";
}
<head>
    <link rel="stylesheet" href="~/css/Quiz.css">
</head>

<body>
    <div>
        <h1>Edit Quiz</h1>
        <form method="post">
            <label for="quizTitle">Quiz Title:</label>
            <input type="text" id="quizTitle" name="Title" value="@Model.Quiz.Title" required>
            <span asp-validation-for="@Model.Quiz.Title"></span>

            <label for="quizDescription">Quiz Description:</label>
            <textarea id="quizDescription" name="Description" rows="4" required>@Model.Quiz.Description</textarea>
            <span asp-validation-for="@Model.Quiz.Description"></span>
            <button type="submit">Save Quiz Detail</button>
        </form>
    </div>

    <div>
        <h1>Quiz Questions</h1>
        <hr>
        <button id="addQuestion">Add Questions</button>
        <form method="post" id="quizForm">
            @{
                var index = 1;
            }
            <ul id="questionsList">
                @foreach (var question in @Model.QuestionList) {
                    <li class="quiz-container">
                        <label>Question @index</label>
                        <input type="text" name="Question@(index)" class="question-input" value="@question.Content" required>

                        <label for="option1">Option 1:</label>
                        <input type="text" id="option1" name="Option1_@(index)" class="option-input" value="@question.Option1" required>

                        <label for="option2">Option 2:</label>
                        <input type="text" id="option2" name="Option2_@(index)" class="option-input" value="@question.Option2" required>

                        <label for="option3">Option 3:</label>
                        <input type="text" id="option3" name="Option3_@(index)" class="option-input" value="@question.Option3" required>

                        <label for="option4">Option 4:</label>
                        <input type="text" id="option4" name="Option4_@(index)" class="option-input" value="@question.Option4" required>

                        <label for="correctAnswer">Correct Answer (Enter Option Number):</label>
                        <input type="text" id="correctAnswer" name="CorrectAnswer_@(index)" value="@question.CorrectAnswerId" required>
                    </li>
                    index++;
                }
            </ul>
            <input type="hidden" id="questionCount" name="QuestionCount" value="@Model.QuestionList.Count" />
            <input type="hidden" id="quizId" name="QuizId" value="@Model.QuizId" />
            <button type="submit" asp-page-handler="SaveQuestions">Save Questions</button>
        </form>
    </div>
</body>

@section scripts {
    <script>
        document.getElementById('addQuestion').addEventListener('click', function () {
            const questionsList = document.getElementById('questionsList');
            const questionCountInput = document.getElementById('questionCount');
            const newQuestionCount = parseInt(questionCountInput.value) + 1;
            const newQuestion = document.createElement('li');
            newQuestion.classList.add('quiz-container');

            // Construct the inner HTML for the new question
            newQuestion.innerHTML = `
                <label>Question ${newQuestionCount}</label>
                <input type="text" name="Question${newQuestionCount}" class="question-input" required>
                <label for="option1">Option 1:</label>
                <input type="text" id="option1" name="Option1_${newQuestionCount}" class="option-input" required>
                <label for="option2">Option 2:</label>
                <input type="text" id="option2" name="Option2_${newQuestionCount}" class="option-input" required>
                <label for="option3">Option 3:</label>
                <input type="text" id="option3" name="Option3_${newQuestionCount}" class="option-input" required>
                <label for="option3">Option 4:</label>
                <input type="text" id="option4" name="Option4_${newQuestionCount}" class="option-input" required>
                <label for="correctAnswer">Correct Answer (Enter Option Number):</label>
                <input type="text" id="correctAnswer" name="CorrectAnswer_${newQuestionCount}" required>
            `;

            questionsList.appendChild(newQuestion);
            questionCountInput.value = newQuestionCount;
        });
    </script>
}

QuizApplication/QuizApplication/Pages/Quizzes.cshtml
@page 
@model QuizApplication.Pages.QuizzesModel
@{
    ViewData["Title"] = "Home Page";
}

<body>
    <div class="container">
        <h1>List of Quizzes</h1>
        <ul class="quiz-list">
            @foreach (var _quiz in Model.Quizzes)
            {
                <li class="quiz-item">
                    <h2>@_quiz.Title</h2>
                    <p>@_quiz.Description</p>
                    <a href="/Quiz/Edit?Id=@_quiz.Id">Edit Quiz</a>
                    <a href="/StartQuiz?Id=@_quiz.Id">Start Quiz</a>
                </li>
            }
        </ul>
        <a href="/AddQuiz" class="add-quiz-button"></a>
    </div>
</body>

QuizApplication/QuizApplication/Pages/ScoreBoard.cshtml
@page 
@model QuizApplication.Pages.ScoreBoardModel
@{
    ViewData["Title"] = "Score Board";
}

<body>
    <div class="p-5 text-center bg-body-secondary m-1 mb-3 shadow">
        <h1 class="mb-3">SCORE BOARD</h1>
    </div>
    <div class="p-5 mb-3 text-center shadow">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Rank</th>
                    <th scope="col">User Name</th>
                    <th scope="col">Score</th>
                </tr>
            </thead>
            <tbody>
                @{
                    int rank = 1;
                }
                @foreach(var UserScore in Model.UserScoresList)
                {
                    <tr>
                        <th scope="row">@rank</th>
                        <td>@UserScore.UserName</td>
                        <td>@UserScore.Score</td>
                    </tr>
                    rank++;
                }
            </tbody>
        </table>
    </div>
    <div class="text-center">
        <a href="/Quizzes" class="btn btn-primary btn-lg">Home Page</a>
    </div>

</body>

QuizApplication/QuizApplication/Pages/SignUp.cshtml
@page
@model QuizApplication.Pages.SignUpModel
@{
    ViewData["Title"] = "Sign Up";
}

<link rel="stylesheet" href="/QuizApplication.styles.css" />

<div class="text-center">
    <div class="login-container">
        <h2>Create an account</h2>
        <form method="post">
            <div class="form-group">
                <label for="username">Username:</label>
                <input type="text" id="username" name="UserName" placeholder="User Name" required>
                <span asp-validation-for="@Model.User.UserName"></span>
            </div>  
            <div class="form-group">
                <label for="email">Email:</label>
                <input type="text" id="email" name="UserEmail" placeholder="Email" required>
                <span asp-validation-for="@Model.User.UserEmail"></span>
            </div>
            <div class="form-group">
                <label for="password">Phone Number:</label>
                <input style="width: 100%" type="number" id="phone" name="Phone" placeholder="Phone Number" required>
                <span asp-validation-for="@Model.User.Phone"></span>
            </div>
            <div class="form-group">
                <label for="password">Password:</label>
                <input type="password" id="password" name="HashPassword" placeholder="Password" required>
                <span asp-validation-for="@Model.User.HashPassword"></span>
            </div>
            <button type="submit">Sign Up</button>
        </form>
    </div>
</div>

QuizApplication/QuizApplication/Pages/StartQuiz.cshtml
@page 
@model QuizApplication.Pages.StartQuizModel
@{
    ViewData["Title"] = "Quiz";
}

<body>
    <div class="p-5 text-center bg-body-secondary m-1 mb-3 shadow">
        <h1 class="mb-3">@Model.Quiz.Title</h1>
        <span asp-validation-for="@Model.Quiz.Title"></span>
    </div>

    <div class="shadow p-5 bg-body-secondary">
        <form method="post">
            <ul class="list-unstyled">
                @{
                    int index = 1;
                }
                @foreach (var question in Model.QuestionsList)
                {
                    <li class="mb-5 p-3" style="background-color: #E9ECEF">
                        <label class="fw-bold h5">@question.Content</label>
                        <div class="form-check">
                            <input class="form-check-input" type="radio" name="@question.Id _@index" id="Option1" value="1">
                            <label class="form-check-label" for="Option1">
                                @question.Option1
                            </label>
                        </div>
                        <div class="form-check">
                            <input class="form-check-input" type="radio" name="@question.Id _@index" id="Option2" value="2">
                            <label class="form-check-label" for="Option2">
                                @question.Option2
                            </label>
                        </div>
                        <div class="form-check">
                            <input class="form-check-input" type="radio" name="@question.Id _@index" id="Option3" value="3">
                            <label class="form-check-label" for="Option3">
                                @question.Option3
                            </label>
                        </div>
                        <div class="form-check">
                            <input class="form-check-input" type="radio" name="@question.Id _@index" id="Option4" value="4">
                            <label class="form-check-label" for="Option4">
                                @question.Option4
                            </label>
                        </div>
                        <input type="hidden" id="questionId" name="QuestionId_@index" value="@question.Id" />
                    </li>
                    index++;
                }
            </ul>
            <input type="hidden" id="quizId" name="QuizId" value="@Model.QuizId" />
            <div class="text-center">            
                <button type="submit" class="btn btn-primary btn-lg">Submit</button>
            </div>
        </form>
    </div>
</body>